title: Cristian IA # your name (or website title) here
logo: "/assets/img/kured1.png?raw=true" # your photo (or logo) here
description: > I am a simple person who admires technological advancement, who seeks to get the best out of the opportunities offered by the internet, growing as a person, and developing my own company little by little # your text below (remove <br> elements if you don't need line breaks)
  
  <a href="https://www.linkedin.com/in/cristian-javier-ibadango-avilez-7726941a5/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
